### ISSUE TITLE
Update tailwind setup

### ISSUE THREAD

**Issue by jasminetracey** [zaengle/craft-baseline#45]
**Description**

- [x]  Add tailwind forms to base setup [https://github.com/tailwindlabs/tailwindcss-typography](https://github.com/tailwindlabs/tailwindcss-typography)

- [x]  Change `sr-only` to `skip-link` and update the styling to something basic

``` CSS
.skip-link {
    @apply absolute left-0 p-4 text-white bg-black -top-16;
    z-index: 100;

    &:focus {
      @apply top-0 outline-none outline-blue-500;
    }
  }
```
